/*
 * SWAPI2
 * defaultDescription
 *
 * OpenAPI spec version: 1.0.0
 * Contact: email@email.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2005
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-22T17:13:49.696677300Z[GMT]")

public class InlineResponse2005 {
  @SerializedName("films")
  private List<String> films = null;

  @SerializedName("skin_colors")
  private String skinColors = null;

  @SerializedName("homeworld")
  private String homeworld = null;

  @SerializedName("edited")
  private String edited = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("eye_colors")
  private String eyeColors = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("classification")
  private String classification = null;

  @SerializedName("people")
  private List<String> people = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("hair_colors")
  private String hairColors = null;

  @SerializedName("average_height")
  private String averageHeight = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("designation")
  private String designation = null;

  @SerializedName("average_lifespan")
  private String averageLifespan = null;

  public InlineResponse2005 films(List<String> films) {
    this.films = films;
    return this;
  }

  public InlineResponse2005 addFilmsItem(String filmsItem) {
    if (this.films == null) {
      this.films = new ArrayList<String>();
    }
    this.films.add(filmsItem);
    return this;
  }

   /**
   * Get films
   * @return films
  **/
  @Schema(description = "")
  public List<String> getFilms() {
    return films;
  }

  public void setFilms(List<String> films) {
    this.films = films;
  }

  public InlineResponse2005 skinColors(String skinColors) {
    this.skinColors = skinColors;
    return this;
  }

   /**
   * Get skinColors
   * @return skinColors
  **/
  @Schema(description = "")
  public String getSkinColors() {
    return skinColors;
  }

  public void setSkinColors(String skinColors) {
    this.skinColors = skinColors;
  }

  public InlineResponse2005 homeworld(String homeworld) {
    this.homeworld = homeworld;
    return this;
  }

   /**
   * Get homeworld
   * @return homeworld
  **/
  @Schema(description = "")
  public String getHomeworld() {
    return homeworld;
  }

  public void setHomeworld(String homeworld) {
    this.homeworld = homeworld;
  }

  public InlineResponse2005 edited(String edited) {
    this.edited = edited;
    return this;
  }

   /**
   * Get edited
   * @return edited
  **/
  @Schema(description = "")
  public String getEdited() {
    return edited;
  }

  public void setEdited(String edited) {
    this.edited = edited;
  }

  public InlineResponse2005 created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public InlineResponse2005 eyeColors(String eyeColors) {
    this.eyeColors = eyeColors;
    return this;
  }

   /**
   * Get eyeColors
   * @return eyeColors
  **/
  @Schema(description = "")
  public String getEyeColors() {
    return eyeColors;
  }

  public void setEyeColors(String eyeColors) {
    this.eyeColors = eyeColors;
  }

  public InlineResponse2005 language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public InlineResponse2005 classification(String classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Get classification
   * @return classification
  **/
  @Schema(description = "")
  public String getClassification() {
    return classification;
  }

  public void setClassification(String classification) {
    this.classification = classification;
  }

  public InlineResponse2005 people(List<String> people) {
    this.people = people;
    return this;
  }

  public InlineResponse2005 addPeopleItem(String peopleItem) {
    if (this.people == null) {
      this.people = new ArrayList<String>();
    }
    this.people.add(peopleItem);
    return this;
  }

   /**
   * Get people
   * @return people
  **/
  @Schema(description = "")
  public List<String> getPeople() {
    return people;
  }

  public void setPeople(List<String> people) {
    this.people = people;
  }

  public InlineResponse2005 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public InlineResponse2005 hairColors(String hairColors) {
    this.hairColors = hairColors;
    return this;
  }

   /**
   * Get hairColors
   * @return hairColors
  **/
  @Schema(description = "")
  public String getHairColors() {
    return hairColors;
  }

  public void setHairColors(String hairColors) {
    this.hairColors = hairColors;
  }

  public InlineResponse2005 averageHeight(String averageHeight) {
    this.averageHeight = averageHeight;
    return this;
  }

   /**
   * Get averageHeight
   * @return averageHeight
  **/
  @Schema(description = "")
  public String getAverageHeight() {
    return averageHeight;
  }

  public void setAverageHeight(String averageHeight) {
    this.averageHeight = averageHeight;
  }

  public InlineResponse2005 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2005 designation(String designation) {
    this.designation = designation;
    return this;
  }

   /**
   * Get designation
   * @return designation
  **/
  @Schema(description = "")
  public String getDesignation() {
    return designation;
  }

  public void setDesignation(String designation) {
    this.designation = designation;
  }

  public InlineResponse2005 averageLifespan(String averageLifespan) {
    this.averageLifespan = averageLifespan;
    return this;
  }

   /**
   * Get averageLifespan
   * @return averageLifespan
  **/
  @Schema(description = "")
  public String getAverageLifespan() {
    return averageLifespan;
  }

  public void setAverageLifespan(String averageLifespan) {
    this.averageLifespan = averageLifespan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.films, inlineResponse2005.films) &&
        Objects.equals(this.skinColors, inlineResponse2005.skinColors) &&
        Objects.equals(this.homeworld, inlineResponse2005.homeworld) &&
        Objects.equals(this.edited, inlineResponse2005.edited) &&
        Objects.equals(this.created, inlineResponse2005.created) &&
        Objects.equals(this.eyeColors, inlineResponse2005.eyeColors) &&
        Objects.equals(this.language, inlineResponse2005.language) &&
        Objects.equals(this.classification, inlineResponse2005.classification) &&
        Objects.equals(this.people, inlineResponse2005.people) &&
        Objects.equals(this.url, inlineResponse2005.url) &&
        Objects.equals(this.hairColors, inlineResponse2005.hairColors) &&
        Objects.equals(this.averageHeight, inlineResponse2005.averageHeight) &&
        Objects.equals(this.name, inlineResponse2005.name) &&
        Objects.equals(this.designation, inlineResponse2005.designation) &&
        Objects.equals(this.averageLifespan, inlineResponse2005.averageLifespan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(films, skinColors, homeworld, edited, created, eyeColors, language, classification, people, url, hairColors, averageHeight, name, designation, averageLifespan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("    films: ").append(toIndentedString(films)).append("\n");
    sb.append("    skinColors: ").append(toIndentedString(skinColors)).append("\n");
    sb.append("    homeworld: ").append(toIndentedString(homeworld)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    eyeColors: ").append(toIndentedString(eyeColors)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    people: ").append(toIndentedString(people)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    hairColors: ").append(toIndentedString(hairColors)).append("\n");
    sb.append("    averageHeight: ").append(toIndentedString(averageHeight)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    designation: ").append(toIndentedString(designation)).append("\n");
    sb.append("    averageLifespan: ").append(toIndentedString(averageLifespan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
