/*
 * SWAPI2
 * defaultDescription
 *
 * OpenAPI spec version: 1.0.0
 * Contact: email@email.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse2004;
import io.swagger.client.model.InlineResponse2005;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiPlanets1GetTest() throws Exception {
        InlineResponse2001 response = api.apiPlanets1Get();

        // TODO: test validations
    }
    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiPlanetsGetTest() throws Exception {
        String search = null;
        InlineResponse2002 response = api.apiPlanetsGet(search);

        // TODO: test validations
    }
    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiPlanetsSchemaGetTest() throws Exception {
        InlineResponse200 response = api.apiPlanetsSchemaGet();

        // TODO: test validations
    }
    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiSpecies3GetTest() throws Exception {
        InlineResponse2005 response = api.apiSpecies3Get();

        // TODO: test validations
    }
    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiSpeciesGetTest() throws Exception {
        String search = null;
        InlineResponse2004 response = api.apiSpeciesGet(search);

        // TODO: test validations
    }
    /**
     * 
     *
     * Auto generated using Swagger Inspector
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void apiSpeciesSchemaGetTest() throws Exception {
        InlineResponse2003 response = api.apiSpeciesSchemaGet();

        // TODO: test validations
    }
}
